job:
  image: hmctspublic.azurecr.io/_/dashboard-ingestion:latest
  aadIdentityName: _
  keyVaults:
    vaultOne:
      secrets:
        - name: secret-one
          alias: SECRET_ONE_ALIAS
        - secret_Two
    vaultTwo:
      secrets:
        - secret-three
        - secret_Four
  schedule: "0/10 * * * *"
global:
  jobKind: CronJob
  enableKeyVaults: true
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
