name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile
      - run: yarn run build --if-present
      - run: yarn lint
      - run: yarn test
      - run: yarn coverage
      - run: yarn test:codacy-upload
      - run: yarn test:codecov-upload
